### ISSUE TITLE
Crash on disabling ISIS protocol 

### ISSUE THREAD

**Issue by sachinites** [sachinites/tcpip_stack#29]
Branch : **NewLsdb**
Topology : **build_dualswitch_topo**
Steps to repro Crash : 
conf node H1 protocol isis
conf node H1 protocol isis interface all
conf node H2 protocol isis
conf node H2 protocol isis interface all
conf node H2 no protocol isis  <<  repro the crash.

The crash is related to memory corruption. Issue is reproducible even when Mem Mgr Lib is disintegrated with the application.

**BT  : (when Mem Mgr is integrated )**
**Repro 1 :**
Thread 6 "tcpstack.exe" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff52c4700 (LWP 11865)]
0x0000555555574edd in mm_free_blocks (to_be_free_block=0x7fffe898c82e) at LinuxMemoryManager/mm.c:680
680         if(next_block && next_block->is_free == MM_TRUE){
(gdb) bt
#0  0x0000555555574edd in mm_free_blocks (to_be_free_block=0x7fffe898c82e) at LinuxMemoryManager/mm.c:680
#1  0x000055555557500d in xfree (app_data=0x7fffe898c85e) at LinuxMemoryManager/mm.c:720
#2  0x000055555559eed8 in tcp_ip_free_pkt_buffer (pkt=0x7fffe898cfbd "\377\377\377\377\377\377\210\343", <incomplete sequence \307>, pkt_size=33) at ../../net.h:175
#3  0x00005555555a0dc1 in isis_deref_isis_pkt (node=0x55555566ecb0, lsp_pkt=0x7fffe8999050) at isis_pkt.c:894
#4  0x00005555555ab77e in isis_fragment_dealloc_lsp_pkt (node=0x55555566ecb0, fragment=0x7fffe899c150) at isis_advt.cpp:597
#5  0x00005555555ab1ec in isis_discard_fragment (node=0x55555566ecb0, fragment=0x7fffe899c150) at isis_advt.cpp:440
#6  0x00005555555aafa0 in isis_destroy_advt_db (node=0x55555566ecb0, pn_no=0 '\000') at isis_advt.cpp:391
#7  0x000055555559c639 in isis_protocol_shutdown_now (node=0x55555566ecb0) at isis_rtr.c:121
#8  0x000055555559c707 in isis_check_and_shutdown_protocol_now (node=0x55555566ecb0, work_completed_flag=1) at isis_rtr.c:148
#9  0x00005555555a180f in isis_lsp_xmit_job (ev_dis=0x55555566eff0, arg=0x7ffff49fded0, arg_size=0) at isis_flood.c:133
#10 0x0000555555571cf0 in event_dispatcher_thread (arg=0x55555566eff0) at EventDispatcher/event_dispatcher.c:217
#11 0x00007ffff7fa3609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#12 0x00007ffff7c71133 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
(gdb) run

**BT when MEM mgr is disintegrated.**
**Repro 2 :** 
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff7b74859 in __GI_abort () at abort.c:79
#2  0x00007ffff7bdf26e in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7ffff7d09298 "%s\n") at ../sysdeps/posix/libc_fatal.c:155
#3  0x00007ffff7be72fc in malloc_printerr (str=str@entry=0x7ffff7d074c1 "free(): invalid pointer") at malloc.c:5347
#4  0x00007ffff7be8b2c in _int_free (av=<optimized out>, p=<optimized out>, have_lock=0) at malloc.c:4173
#5  0x000055555559ee03 in tcp_ip_free_pkt_buffer (pkt=0x7fffe8004dbd "\377\377\377\377\377\377\210\343", <incomplete sequence \307>, pkt_size=33) at ../../net.h:175
#6  0x00005555555a0ce1 in isis_deref_isis_pkt (node=0x55555566f0e0, lsp_pkt=0x7fffe8006610) at isis_pkt.c:894
#7  0x00005555555ab65b in isis_fragment_dealloc_lsp_pkt (node=0x55555566f0e0, fragment=0x7fffe8003be0) at isis_advt.cpp:597
#8  0x00005555555ab0c9 in isis_discard_fragment (node=0x55555566f0e0, fragment=0x7fffe8003be0) at isis_advt.cpp:440
#9  0x00005555555aae7d in isis_destroy_advt_db (node=0x55555566f0e0, pn_no=0 '\000') at isis_advt.cpp:391
#10 0x000055555559c57d in isis_protocol_shutdown_now (node=0x55555566f0e0) at isis_rtr.c:121
#11 0x000055555559c64b in isis_check_and_shutdown_protocol_now (node=0x55555566f0e0, work_completed_flag=1) at isis_rtr.c:148
#12 0x00005555555a172f in isis_lsp_xmit_job (ev_dis=0x55555566f420, arg=0x7ffff5210c80, arg_size=0) at isis_flood.c:133
#13 0x0000555555571c83 in event_dispatcher_thread (arg=0x55555566f420) at EventDispatcher/event_dispatcher.c:217
#14 0x00007ffff7fa3609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#15 0x00007ffff7c71133 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
(gdb)

**Tried again without gdb attached (Mem Mgr Disintegrated)**
**Repro 3:**
Soft-FireWall> $ conf node H2 no pro isis
Parse Success.
CLI returned

free(): invalid pointer

**Comment by sachinites** [comment]
Issue resolved.
