### ISSUE TITLE
Crash reported when running the testcase

### ISSUE THREAD

**Issue by sachinites** [sachinites/tcpip_stack#30]
Topology loaded : **cross_link_topology**

Crash happens like 2 times out of 5 times.

Soft-Firewall>$ run ut Layer5/isis/ut/isis_tc.ut 2
```
free(): invalid pointer
Thread 6 "tcpstack.exe" received signal SIGABRT, Aborted.
[Switching to Thread 0x7ffff517e640 (LWP 26561)]
__pthread_kill_implementation (no_tid=0, signo=6, threadid=140737305372224) at ./nptl/pthread_kill.c:44
44      ./nptl/pthread_kill.c: No such file or directory.
(gdb) bt
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=140737305372224) at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=140737305372224) at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=140737305372224, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
#3  0x00007ffff7adb476 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#4  0x00007ffff7ac17f3 in __GI_abort () at ./stdlib/abort.c:79
#5  0x00007ffff7b226f6 in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7ffff7c74b8c "%s\n") at ../sysdeps/posix/libc_fatal.c:155
#6  0x00007ffff7b39d7c in malloc_printerr (str=str@entry=0x7ffff7c72764 "free(): invalid pointer") at ./malloc/malloc.c:5664
#7  0x00007ffff7b3bac4 in _int_free (av=<optimized out>, p=<optimized out>, have_lock=0) at ./malloc/malloc.c:4439
#8  0x00007ffff7b3e4d3 in __GI___libc_free (mem=<optimized out>) at ./malloc/malloc.c:3391
#9  0x00005555555b2f1f in tcp_ip_free_pkt_buffer (pkt=0x7fffe4001315 "\377\377\377\377\377\377", pkt_size=93) at ../../net.h:183
#10 0x00005555555b4989 in isis_deref_isis_pkt (node=0x7ffff6b8f760, lsp_pkt=0x7fffe4000b70) at isis_pkt.c:681
#11 0x00005555555b53b3 in isis_lsp_xmit_job (ev_dis=0x7ffff6b8fab8, arg=0x7ffff6ba7740, arg_size=0) at isis_flood.c:99
#12 0x000055555557d5f2 in event_dispatcher_thread (arg=0x7ffff6b8fab8) at EventDispatcher/event_dispatcher.c:220
#13 0x00007ffff7b2db43 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
#14 0x00007ffff7bbfa00 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
(gdb) 
```

**Comment by sachinites** [comment]
issue is not seen anymore as on 21 nov 2024.
