### ISSUE TITLE
DCB :  ISIS Crashes as soon as TC is triggered in isis_tc.ut on cross_link_topology 

### ISSUE THREAD

**Issue by sachinites** [sachinites/tcpip_stack#35]
Branch DCB ( latest )
Crashes as soon as TC is triggered in isis_tc.ut 
Topology : cross_link_topology 
git commit : efcbea09512d9e1d5ddd675c733c16b08d886dcb

Soft-Firewall>$ run ut Layer5/isis/ut/isis_tc.ut 2
                                                  Thread 2 "tcpstack.exe" received signal SIGSEGV, Segmentation fault.
                                                                                                                      [Switching to Thread 0xfffff660ef40 (LWP 1114431)]
0x0000aaaaaaaa7e58 in avltree_insert (node=0xfffff7e9e1d8, tree=0xfffff7eec050) at Tree/avl.c:299
299                     if (parent->left == node)
(gdb) bt
#0  0x0000aaaaaaaa7e58 in avltree_insert (node=0xfffff7e9e1d8, tree=0xfffff7eec050) at Tree/avl.c:299
#1  0x0000aaaaaaad4118 in ted_insert_node_in_teddb (ted_db=0xfffff7eec050, node=0xfffff7e9e30b) at ted/ted.c:301
#2  0x0000aaaaaaad4790 in ted_create_or_update_node (ted_db=0xfffff7eec050, template_node_data=0xfffff7e938e0, prefix_tree_root=0x0) at ted/ted.c:489
#3  0x0000aaaaaab15af0 in isis_ted_update_or_install_lsp (node=0xaaaaaac2c3e0, lsp_pkt=0xfffff7ee4218) at isis_ted.c:115
#4  0x0000aaaaaab0e898 in isis_install_lsp (node=0xaaaaaac2c3e0, iif=0x0, new_lsp_pkt=0xfffff7ee4218) at isis_lspdb.c:156
#5  0x0000aaaaaab18e6c in isis_lsp_fragment_regen_cbk (ev_dis=0xaaaaaac2c740, arg=0xaaaaaac2c3e0, arg_size=0) at isis_advt.cpp:148
#6  0x0000aaaaaaad28d4 in event_dispatcher_thread (arg=0xaaaaaac2c740) at EventDispatcher/event_dispatcher.c:219
#7  0x0000fffff7a8597c in start_thread (arg=0xfffff7fbadc0) at ./nptl/pthread_create.c:447
#8  0x0000fffff7aeba4c in thread_start () at ../sysdeps/unix/sysv/linux/aarch64/clone3.S:76
(gdb) 

This could be because of memory corruption.

**Comment by sachinites** [comment]
Resolved 
git comit :  e30ac8e5fd523a0e7921c9f8e58b96c57e3be129
