### ISSUE TITLE
Branch DCB-traceback on running TC almost immediately

### ISSUE THREAD

**Issue by sachinites** [sachinites/tcpip_stack#36]
Branch DCB-traceback

Soft-Firewall>$ run ut Layer5/isis/ut/isis_tc.ut 0

tcpstack.exe: Layer3/layer3.c:393: void clear_rt_table(rt_table_t*, uint16_t): Assertion `l3_route' failed.
Thread 12 "tcpstack.exe" received signal SIGABRT, Aborted.

   [Switching to Thread 0xfffff0c0ef40 (LWP 1096372)]
__pthread_kill_implementation (threadid=281474720919360, signo=signo@entry=6, no_tid=no_tid@entry=0) at ./nptl/pthread_kill.c:44
warning: 44     ./nptl/pthread_kill.c: No such file or directory
(gdb) bt
#0  __pthread_kill_implementation (threadid=281474720919360, signo=signo@entry=6, no_tid=no_tid@entry=0) at ./nptl/pthread_kill.c:44
#1  0x0000fffff7a87690 in __pthread_kill_internal (signo=6, threadid=<optimized out>) at ./nptl/pthread_kill.c:78
#2  0x0000fffff7a3cb3c in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#3  0x0000fffff7a27e00 in __GI_abort () at ./stdlib/abort.c:79
#4  0x0000fffff7a35cbc in __assert_fail_base (fmt=0xfffff7b5c6d0 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=assertion@entry=0xaaaaaab18a10 "l3_route",
    file=file@entry=0xaaaaaab18918 "Layer3/layer3.c", line=line@entry=393, function=function@entry=0xaaaaaab189e0 "void clear_rt_table(rt_table_t*, uint16_t)") at ./assert/assert.c:94
#5  0x0000fffff7a35d2c in __assert_fail (assertion=0xaaaaaab18a10 "l3_route", file=0xaaaaaab18918 "Layer3/layer3.c", line=393, function=0xaaaaaab189e0 "void clear_rt_table(rt_table_t*, uint16_t)")
    at ./assert/assert.c:103
#6  0x0000aaaaaaaba720 in clear_rt_table (rt_table=0xfffff7ff13c8, proto_id=131) at Layer3/layer3.c:393
#7  0x0000aaaaaaaffa6c in isis_schedule_route_delete_task (node=0xaaaaaac28a80, event_type=isis_event_admin_action_shutdown_pending) at isis_rtr.c:180
#8  0x0000aaaaaaaffb80 in isis_launch_prior_shutdown_tasks (node=0xaaaaaac28a80) at isis_rtr.c:213
#9  0x0000aaaaaaaffc8c in isis_protocol_shut_down (node=0xaaaaaac28a80) at isis_rtr.c:252
#10 0x0000aaaaaab000d4 in isis_de_init (node=0xaaaaaac28a80) at isis_rtr.c:340
#11 0x0000aaaaaaafc728 in isis_config_handler (cmdcode=1, tlv_stack=0xffffdc008870, enable_or_disable=CONFIG_DISABLE) at isis_cli.c:234
#12 0x0000aaaaaaaab488 in task_cbk_handler_internal (ev_dis=0xaaaaaac28de0, arg=0xffffdc004750, arg_size=0) at cli_interface.c:47
#13 0x0000aaaaaaacc608 in event_dispatcher_thread (arg=0xaaaaaac28de0) at EventDispatcher/event_dispatcher.c:219
#14 0x0000fffff7a8597c in start_thread (arg=0xfffff7fbadc0) at ./nptl/pthread_create.c:447
#15 0x0000fffff7aeba4c in thread_start () at ../sysdeps/unix/sysv/linux/aarch64/clone3.S:76
(gdb) bt

**Comment by sachinites** [comment]
under observation to see if this is reproducible.
